<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('users')->delete();
        
		\DB::table('users')->insert(array ( 
			// GURU
			array (
				'id' => 1,
				'nip' => '111101',
				'name' => 'Dra. SUWARNI',
				'email' => 'suwarni',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 2,
				'nip' => '111102',
				'name' => 'Drs. AGUS SUHARHMANTO',
				'email' => 'agussuharmanto',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 3,
				'nip' => '111103',
				'name' => 'Dra. YURI KERTANTI',
				'email' => 'yurikertanti',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 4,
				'nip' => '111104',
				'name' => 'FEBRINA ANGGRAINI, MA.',
				'email' => 'febrinaanggraini',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 5,
				'nip' => '111105',
				'name' => 'TUTUT SULISTYAWATI, S.Pd',
				'email' => 'tututsulistyawati',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 6,
				'nip' => '111106',
				'name' => 'AMALIA IMA N. S.Pd',
				'email' => 'amaliaima',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 7,
				'nip' => '111107',
				'name' => 'Drs. DOMINIKUS DARYADI',
				'email' => 'dominikusdaryadi',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 8,
				'nip' => '111108',
				'name' => 'FEDIKA ARGA RENGGA',
				'email' => 'fedikaargarengga',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 9,
				'nip' => '111109',
				'name' => 'Dra. ZITTA SUSILOWATI',
				'email' => 'zittasusilowati',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 10,
				'nip' => '111110',
				'name' => 'Dra. SUTARTI',
				'email' => 'sutarti',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 11,
				'nip' => '111111',
				'name' => 'SIGIT WIDIASTATA, S.Pd.SI',
				'email' => 'sigitwidiastata',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 12,
				'nip' => '111112',
				'name' => 'Dra. SRI PUJI ASTUTI',
				'email' => 'sripujiastuti',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 13,
				'nip' => '111113',
				'name' => 'NUR AISYAH SA.g',
				'email' => 'nuraisyah',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 14,
				'nip' => '111114',
				'name' => 'DEDDY SETYONO, S FARM',
				'email' => 'deddysetyono',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 15,
				'nip' => '111115',
				'name' => 'YOSEFFIN SUPRATMI, S.Pd',
				'email' => 'yoseffinsupratmi',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 16,
				'nip' => '111116',
				'name' => 'HERA ERWANTI, ST',
				'email' => 'heraerwanti',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 17,
				'nip' => '99999',
				'name' => 'Dark King',
				'email' => 'dk',
				'password' => Hash::make('password'),
				'role' => 'administrator',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 18,
				'nip' => '88888',
				'name' => 'Blue Eyes',
				'email' => 'be',
				'password' => Hash::make('password'),
				'role' => 'administrator',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 19,
				'nip' => '111117',
				'name' => 'GARGARINA SARDIANA, S.Th.',
				'email' => 'gargarinasardiana',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Kristen',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 20,
				'nip' => '111118',
				'name' => 'SAMBAS MUHDIR DEWANTO',
				'email' => 'sambasmuhdirdewanto',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 21,
				'nip' => '111119',
				'name' => 'Dra. SITI RUMINI',
				'email' => 'sitirumini',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 22,
				'nip' => '111120',
				'name' => 'Drs. DALDURI',
				'email' => 'dalduri',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 23,
				'nip' => '111121',
				'name' => 'Dra. DWI MURTI',
				'email' => 'dwimurti',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 24,
				'nip' => '111122',
				'name' => 'SUNARTI, S.Pd.',
				'email' => 'sunarti',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 25,
				'nip' => '111123',
				'name' => 'SUDARMAJI, S.Pd.',
				'email' => 'sudarmaji',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 26,
				'nip' => '111124',
				'name' => 'MM. MURWANI, S.Pd.',
				'email' => 'murwani',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 27,
				'nip' => '111125',
				'name' => 'AGUS PURWANTO, S.Pd.',
				'email' => 'aguspurwanto',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 28,
				'nip' => '111126',
				'name' => 'Dra. ENDAH BUDI LESTARI',
				'email' => 'endahbudilestari',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 29,
				'nip' => '111127',
				'name' => 'Drs. TUKIDJAN HS',
				'email' => 'tukidjan',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 30,
				'nip' => '111128',
				'name' => 'SUGIYANTO',
				'email' => 'sugiyanto',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 31,
				'nip' => '111129',
				'name' => 'B. RETNO DEWI',
				'email' => 'retnodewi',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 32,
				'nip' => '111130',
				'name' => 'Drs. PONIJO',
				'email' => 'ponijo',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 33,
				'nip' => '111131',
				'name' => 'L. SUPIYANTO, B.Sc.',
				'email' => 'supiyanto',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 34,
				'nip' => '111132',
				'name' => 'M. MASHARI, S.Kom.',
				'email' => 'mashari',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 35,
				'nip' => '111133',
				'name' => 'Dra. NUR HAYATI',
				'email' => 'nurhayati',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 36,
				'nip' => '111134',
				'name' => 'Dra. TUTIK SUWARTINI',
				'email' => 'tutiksuwartini',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 37,
				'nip' => '111135',
				'name' => 'HARIYADI, S.Pd.',
				'email' => 'hariyadi',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 38,
				'nip' => '111136',
				'name' => 'Dra. PENI AKHADIYATI',
				'email' => 'peniakhadiyati',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 39,
				'nip' => '111137',
				'name' => 'SUTARKO',
				'email' => 'sutarko',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 40,
				'nip' => '111138',
				'name' => 'DIAN ARI FITRI, S.S.',
				'email' => 'dianarifitri',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			// GURU PIKET
			array (
				'id' => 41,
				'nip' => '111141',
				'name' => 'GURU PIKET 01',
				'email' => 'gurupiket01',
				'password' => Hash::make('password'),
				'role' => 'guru piket',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => 'Senin',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 42,
				'nip' => '111142',
				'name' => 'GURU PIKET 02',
				'email' => 'gurupiket02',
				'password' => Hash::make('password'),
				'role' => 'guru piket',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => 'Selasa',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 43,
				'nip' => '111143',
				'name' => 'GURU PIKET 03',
				'email' => 'gurupiket03',
				'password' => Hash::make('password'),
				'role' => 'guru piket',
				'jkl' => PR,
				'agama' => 'Katolik',
				'tlp' => '',
				'jadwal' => 'Rabu',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 44,
				'nip' => '111144',
				'name' => 'GURU PIKET 04',
				'email' => 'gurupiket04',
				'password' => Hash::make('password'),
				'role' => 'guru piket',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => 'Kamis',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 45,
				'nip' => '111145',
				'name' => 'GURU PIKET 05',
				'email' => 'gurupiket05',
				'password' => Hash::make('password'),
				'role' => 'guru piket',
				'jkl' => PR,
				'agama' => 'Kristen',
				'tlp' => '',
				'jadwal' => 'Jumat',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 46,
				'nip' => '111146',
				'name' => 'GURU PIKET 06',
				'email' => 'gurupiket06',
				'password' => Hash::make('password'),
				'role' => 'guru piket',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => 'Sabtu',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			// TAMU
			array (
				'id' => 47,
				'nip' => '555555',
				'name' => 'TAMU 01',
				'email' => 'tamu01',
				'password' => Hash::make('password'),
				'role' => 'tamu',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 48,
				'nip' => '555556',
				'name' => 'TAMU 02',
				'email' => 'tamu01',
				'password' => Hash::make('password'),
				'role' => 'tamu',
				'jkl' => PR,
				'agama' => 'Kristen',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 49,
				'nip' => '555557',
				'name' => 'TAMU 03',
				'email' => 'tamu03',
				'password' => Hash::make('password'),
				'role' => 'tamu',
				'jkl' => LK,
				'agama' => 'Katolk',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			// ADMINISTRATOR
			array (
				'id' => 50,
				'nip' => '99997',
				'name' => 'ADMIN 01',
				'email' => 'admin01',
				'password' => Hash::make('password'),
				'role' => 'administrator',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 51,
				'nip' => '99998',
				'name' => 'ADMIN 02',
				'email' => 'admin02',
				'password' => Hash::make('password'),
				'role' => 'administrator',
				'jkl' => PR,
				'agama' => 'Kristen',
				'tlp' => '',
				'jadwal' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
		));
	}

}
