<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('users')->delete();
        
		\DB::table('users')->insert(array ( 
			array (
				'id' => 1,
				'nip' => '111101',
				'name' => 'Dra. SUWARNI',
				'email' => 'suwarni',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 2,
				'nip' => '111102',
				'name' => 'Drs. AGUS SUHARHMANTO',
				'email' => 'suharmanto',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 3,
				'nip' => '111103',
				'name' => 'Dra. YURI KERTANTI',
				'email' => 'kertanti',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 4,
				'nip' => '111104',
				'name' => 'FEBRINA ANGGRAINI, MA.',
				'email' => 'anggraini',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 5,
				'nip' => '111105',
				'name' => 'TUTUT SULISTYAWATI, S.Pd',
				'email' => 'sulistyawati',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 6,
				'nip' => '111106',
				'name' => 'AMALIA IMA N. S.Pd',
				'email' => 'amalia',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 7,
				'nip' => '111107',
				'name' => 'Drs. DOMINIKUS DARYADI',
				'email' => 'daryadi',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 8,
				'nip' => '111108',
				'name' => 'FEDIKA ARGA RENGGA',
				'email' => 'fedika',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 9,
				'nip' => '111109',
				'name' => 'Dra. ZITTA SUSILOWATI',
				'email' => 'susilowati',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 10,
				'nip' => '111110',
				'name' => 'Dra. SUTARTI',
				'email' => 'sutarti',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 11,
				'nip' => '111111',
				'name' => 'SIGIT WIDIASTATA, S.Pd.SI',
				'email' => 'widiastata',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 12,
				'nip' => '111112',
				'name' => 'Dra. SRI PUJI ASTUTI',
				'email' => 'astuti',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 13,
				'nip' => '111113',
				'name' => 'NUR AISYAH SA.g',
				'email' => 'aisyah',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 14,
				'nip' => '111114',
				'name' => 'DEDDY SETYONO, S FARM',
				'email' => 'setyono',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 15,
				'nip' => '111115',
				'name' => 'YOSEFFIN SUPRATMI, S.Pd',
				'email' => 'yoseffin',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => LK,
				'agama' => 'Islam',
				'tlp' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 16,
				'nip' => '111116',
				'name' => 'HERA ERWANTI, ST',
				'email' => 'erwanti',
				'password' => Hash::make('password'),
				'role' => 'guru',
				'jkl' => PR,
				'agama' => 'Islam',
				'tlp' => '',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 17,
				'nip' => '99999',
				'name' => 'Dark King',
				'email' => 'dk',
				'password' => Hash::make('password'),
				'role' => 'administrator',
				'jkl' => 'Laki-laki',
				'agama' => 'Islam',
				'tlp' => '0987654321',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
			array (
				'id' => 18,
				'nip' => '88888',
				'name' => 'Blue Eyes',
				'email' => 'be',
				'password' => Hash::make('password'),
				'role' => 'administrator',
				'jkl' => 'Laki-laki',
				'agama' => 'Islam',
				'tlp' => '0987654321',
				'created_at' => '2017-01-07 12:00:00',
				'updated_at' => '2017-01-07 12:01:00',
				'deleted_at' => NULL,
			),
		));
	}

}
